### ISSUE TITLE
Dead link to oroGen API

### ISSUE THREAD

**Issue by maltewi** [rock-core/rock-core.github.io#3]
Link API under "Developing Components" (see image below) points to https://www.rock-robotics.org/api/orogen/index.html. this is a dead link

![image](https://user-images.githubusercontent.com/8180721/55807255-2c120d00-5ae2-11e9-8339-d8fb6b2faa3b.png)

**Comment by 2maz** [comment]
fix in progress #4

**Comment by 2maz** [comment]
Issue is fixed. Also reinstantiated a link to packages API along the way: https://www.rock-robotics.org/apidocs/
