### ISSUE TITLE
Broken Link at Tutorials/Baisics

### ISSUE THREAD

**Issue by maxehrhardt** [rock-core/rock-core.github.io#5]
Clicking at Tutorials/Basics leads to the standard overview site.
Could still reach the tutorials through the URL: 
https://www.rock-robotics.org/documentation/tutorials

**Comment by 2maz** [comment]
Sorry, I cannot reproduce your described behaviour. 
Could you clear you browser cache and verify which link the 'Tutorias/Basics' is pointing to for you:
currently it is https://www.rock-robotics.org/documentation/tutorials/index.html

**Comment by maxehrhardt** [comment]
Clearing Browser Cache helped, now it is working perfectly
